on:
  schedule:
    - cron: '25 * * * *'
  workflow_dispatch:
name: results
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout wpt-results-analysis
      uses: actions/checkout@v2
      with:
        repository: ecosystem-infra/wpt-results-analysis
        ref: main
        fetch-depth: 1
        path: wpt-results-analysis
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 10.x
    - name: Install
      run: npm ci
      working-directory: wpt-results-analysis
    - name: Update
      run: node git-write.js --max-time=3000 --max-age-days=90
      working-directory: wpt-results-analysis
    - name: Push new runs
      run: |
        git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git push origin --tags
      working-directory: wpt-results-analysis/wpt-results.git
